### ISSUE TITLE
Chef 12 compatibility

### ISSUE THREAD

**Issue by alexandre-zia-movile** [jenssegers/php-chef#13]
Hi, we've updated our chef server to 12, and php-chef is not working, something must have been changed in chef 12 API,

**Comment by pelletiermaxime** [comment]
Seems to work fine for me on our chef server 12. I just had to chang the config to set the version to '12.0.0' and 'enterprise' to true.

**Comment by alexandre-zia-movile** [comment]
I've fixed with:

new Jenssegers\Chef\Chef($chef_server_url, $node_name, $client_key, "12.0.1");
